jaffle_shop:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: sc78292.eu-west-3.aws

      # User/password auth
      user: MARTIN
      password: Sifflet123

      role: ACCOUNTADMIN
      database: SIFFLET
      warehouse: COMPUTE_WH
      schema: SIFFLET_TEST_DATA
      threads: 4
      client_session_keep_alive: False
      query_tag: siffletdbt

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false 
      retry_all: False  # default: false      
